(function() {var implementors = {};
implementors["peel_ip"] = ["impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for PathError","impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for PeelError","impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for <a class='struct' href='https://doc.rust-lang.org/time/time/duration/struct.OutOfRangeError.html' title='time::duration::OutOfRangeError'>OutOfRangeError</a>","impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for <a class='enum' href='https://doc.rust-lang.org/time/time/enum.ParseError.html' title='time::ParseError'>ParseError</a>","impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for <a class='enum' href='https://stebalien.github.io/doc/term/term/term/terminfo/enum.Error.html' title='term::terminfo::Error'>Error</a>","impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for <a class='enum' href='https://stebalien.github.io/doc/term/term/term/terminfo/parm/enum.Error.html' title='term::terminfo::parm::Error'>Error</a>","impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for <a class='enum' href='https://stebalien.github.io/doc/term/term/term/enum.Error.html' title='term::Error'>Error</a>","impl&lt;P, E&gt; <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for Err&lt;P, E&gt; <span class='where'>where E: <a class='trait' href='https://doc.rust-lang.org/nightly/core/any/trait.Any.html' title='core::any::Any'>Any</a> + <a class='trait' href='peel_ip/prelude/fmt/trait.Debug.html' title='peel_ip::prelude::fmt::Debug'>Debug</a>, P: <a class='trait' href='https://doc.rust-lang.org/nightly/core/any/trait.Any.html' title='core::any::Any'>Any</a> + <a class='trait' href='peel_ip/prelude/fmt/trait.Debug.html' title='peel_ip::prelude::fmt::Debug'>Debug</a></span>","impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for LogError","impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for <a class='struct' href='https://doc.rust-lang.org/log/log/struct.SetLoggerError.html' title='log::SetLoggerError'>SetLoggerError</a>","impl <a class='trait' href='peel_ip/prelude/trait.Error.html' title='peel_ip::prelude::Error'>Error</a> for <a class='struct' href='https://doc.rust-lang.org/log/log/struct.ShutdownLoggerError.html' title='log::ShutdownLoggerError'>ShutdownLoggerError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
