(function() {var implementors = {};
implementors["peel_ip"] = ["impl <a class='trait' href='peel_ip/prelude/trait.FromStr.html' title='peel_ip::prelude::FromStr'>FromStr</a> for <a class='enum' href='peel_ip/prelude/enum.IpAddr.html' title='peel_ip::prelude::IpAddr'>IpAddr</a>","impl <a class='trait' href='peel_ip/prelude/trait.FromStr.html' title='peel_ip::prelude::FromStr'>FromStr</a> for <a class='struct' href='peel_ip/prelude/struct.Ipv4Addr.html' title='peel_ip::prelude::Ipv4Addr'>Ipv4Addr</a>","impl <a class='trait' href='peel_ip/prelude/trait.FromStr.html' title='peel_ip::prelude::FromStr'>FromStr</a> for <a class='struct' href='peel_ip/prelude/struct.Ipv6Addr.html' title='peel_ip::prelude::Ipv6Addr'>Ipv6Addr</a>","impl <a class='trait' href='peel_ip/prelude/trait.FromStr.html' title='peel_ip::prelude::FromStr'>FromStr</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/net/addr/struct.SocketAddrV4.html' title='std::net::addr::SocketAddrV4'>SocketAddrV4</a>","impl <a class='trait' href='peel_ip/prelude/trait.FromStr.html' title='peel_ip::prelude::FromStr'>FromStr</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/std/net/addr/struct.SocketAddrV6.html' title='std::net::addr::SocketAddrV6'>SocketAddrV6</a>","impl <a class='trait' href='peel_ip/prelude/trait.FromStr.html' title='peel_ip::prelude::FromStr'>FromStr</a> for <a class='enum' href='https://doc.rust-lang.org/nightly/std/net/addr/enum.SocketAddr.html' title='std::net::addr::SocketAddr'>SocketAddr</a>","impl <a class='trait' href='peel_ip/prelude/trait.FromStr.html' title='peel_ip::prelude::FromStr'>FromStr</a> for <a class='enum' href='peel_ip/prelude/enum.LogLevel.html' title='peel_ip::prelude::LogLevel'>LogLevel</a>","impl <a class='trait' href='peel_ip/prelude/trait.FromStr.html' title='peel_ip::prelude::FromStr'>FromStr</a> for <a class='enum' href='https://doc.rust-lang.org/log/log/enum.LogLevelFilter.html' title='log::LogLevelFilter'>LogLevelFilter</a>","impl <a class='trait' href='peel_ip/prelude/trait.FromStr.html' title='peel_ip::prelude::FromStr'>FromStr</a> for <a class='struct' href='https://doc.rust-lang.org/nightly/collections/string/struct.String.html' title='collections::string::String'>String</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
